Repository OS2mo/os2mo-data-import-and-export, pull requests merged in 2020-07, with the labels that each got.

#248 WIP: [#36614] New cronjob
  tools/cron.sh
Labels: enhancement, refactoring

#251 [#31233] Fix rollekatalog manager import
  exporters/os2rollekatalog/os2rollekatalog_integration.py
Labels: bug

#259 sql_export retry mo connection 10 times
  exporters/sql_export/lora_cache.py
Labels: enhancement

#260 Feature/37359 sql export kvittering
  exporters/sql_export/lora_cache.py
  exporters/sql_export/sql_export.py
  exporters/sql_export/sql_table_defs.py
Labels: enhancement
